# Generated by Django 2.1.5 on 2019-01-31 16:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReportModel',
            new_name='Report_Model',
        ),
    ]
