# Generated by Django 2.1.3 on 2018-12-13 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20181212_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('social', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='pool_variant',
            name='belongs_to',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='vote.Pool'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pool',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pool_variant',
            name='variant_name',
            field=models.CharField(max_length=100),
        ),
    ]
