# Generated by Django 2.1.3 on 2018-12-13 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_auto_20181213_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='role',
            field=models.CharField(default='developer', max_length=20),
        ),
        migrations.AlterField(
            model_name='pool_variant',
            name='belongs_to',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='vote.Pool'),
        ),
    ]
